theme: minima
exclude: [README.md]

# TODO: zmenit skolsky rok podla potreby
title: Bakalársky seminár DAV+BIN 2023/24

# TODO: zmenit cislo triedy v moodle podla semestra
# ZS: 3302 LS: 3303
# zvycajne zostane rovnake medzi rokmi
moodle: 3303

# TODO: zmenit podla semestra ZS/LS
header_pages:
  - index.md
  - Pravidlá_LS.md 
  - Kontakt.md
  - Návod.md
  - Školitelia.md
  
